language: node_js
node_js:
  - 15

git:
  depth: false
  quiet: true

cache: yarn

# GitHub Pages 默认使用 jekyll 生成资源，jekyll 默认的配置会忽略以下划线开头的目录，这导致 _next 目录无法访问。
#
# 本站已用 Next.js 的导出命令生成了静态网站，故没有必要再用 jekyll 再处理一遍。
# 在根目录添加 .nojekyll 文件可以禁用 jekyll。
#
#【GitHub Pages 中 jekyll 的说明】
# https://docs.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators
# https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
script:
  - yarn build
  - echo "resume.kaciras.com" > out/CNAME
  - touch out/.nojekyll

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: out
  provider: pages
  skip_cleanup: true
  on:
    branch: master
